// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: xuezh/v1/xuezh.proto

package xuezhv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/joshp123/xuezh/api/xuezh/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// XuezhServiceName is the fully-qualified name of the XuezhService service.
	XuezhServiceName = "xuezh.v1.XuezhService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// XuezhServiceGetLearnerStateProcedure is the fully-qualified name of the XuezhService's
	// GetLearnerState RPC.
	XuezhServiceGetLearnerStateProcedure = "/xuezh.v1.XuezhService/GetLearnerState"
	// XuezhServiceGetSnapshotProcedure is the fully-qualified name of the XuezhService's GetSnapshot
	// RPC.
	XuezhServiceGetSnapshotProcedure = "/xuezh.v1.XuezhService/GetSnapshot"
	// XuezhServiceStartReviewProcedure is the fully-qualified name of the XuezhService's StartReview
	// RPC.
	XuezhServiceStartReviewProcedure = "/xuezh.v1.XuezhService/StartReview"
	// XuezhServiceGradeReviewProcedure is the fully-qualified name of the XuezhService's GradeReview
	// RPC.
	XuezhServiceGradeReviewProcedure = "/xuezh.v1.XuezhService/GradeReview"
	// XuezhServiceBuryReviewProcedure is the fully-qualified name of the XuezhService's BuryReview RPC.
	XuezhServiceBuryReviewProcedure = "/xuezh.v1.XuezhService/BuryReview"
	// XuezhServicePreviewSRSProcedure is the fully-qualified name of the XuezhService's PreviewSRS RPC.
	XuezhServicePreviewSRSProcedure = "/xuezh.v1.XuezhService/PreviewSRS"
	// XuezhServiceReportHSKProcedure is the fully-qualified name of the XuezhService's ReportHSK RPC.
	XuezhServiceReportHSKProcedure = "/xuezh.v1.XuezhService/ReportHSK"
	// XuezhServiceReportMasteryProcedure is the fully-qualified name of the XuezhService's
	// ReportMastery RPC.
	XuezhServiceReportMasteryProcedure = "/xuezh.v1.XuezhService/ReportMastery"
	// XuezhServiceReportDueProcedure is the fully-qualified name of the XuezhService's ReportDue RPC.
	XuezhServiceReportDueProcedure = "/xuezh.v1.XuezhService/ReportDue"
	// XuezhServiceSynthesizeSpeechProcedure is the fully-qualified name of the XuezhService's
	// SynthesizeSpeech RPC.
	XuezhServiceSynthesizeSpeechProcedure = "/xuezh.v1.XuezhService/SynthesizeSpeech"
	// XuezhServiceProcessVoiceProcedure is the fully-qualified name of the XuezhService's ProcessVoice
	// RPC.
	XuezhServiceProcessVoiceProcedure = "/xuezh.v1.XuezhService/ProcessVoice"
	// XuezhServicePutContentProcedure is the fully-qualified name of the XuezhService's PutContent RPC.
	XuezhServicePutContentProcedure = "/xuezh.v1.XuezhService/PutContent"
	// XuezhServiceGetContentProcedure is the fully-qualified name of the XuezhService's GetContent RPC.
	XuezhServiceGetContentProcedure = "/xuezh.v1.XuezhService/GetContent"
	// XuezhServiceLogEventProcedure is the fully-qualified name of the XuezhService's LogEvent RPC.
	XuezhServiceLogEventProcedure = "/xuezh.v1.XuezhService/LogEvent"
	// XuezhServiceListEventsProcedure is the fully-qualified name of the XuezhService's ListEvents RPC.
	XuezhServiceListEventsProcedure = "/xuezh.v1.XuezhService/ListEvents"
	// XuezhServiceDoctorProcedure is the fully-qualified name of the XuezhService's Doctor RPC.
	XuezhServiceDoctorProcedure = "/xuezh.v1.XuezhService/Doctor"
)

// XuezhServiceClient is a client for the xuezh.v1.XuezhService service.
type XuezhServiceClient interface {
	GetLearnerState(context.Context, *connect.Request[v1.GetLearnerStateRequest]) (*connect.Response[v1.LearnerState], error)
	GetSnapshot(context.Context, *connect.Request[v1.GetSnapshotRequest]) (*connect.Response[v1.ReportPayload], error)
	StartReview(context.Context, *connect.Request[v1.StartReviewRequest]) (*connect.Response[v1.StartReviewResponse], error)
	GradeReview(context.Context, *connect.Request[v1.GradeReviewRequest]) (*connect.Response[v1.GradeReviewResponse], error)
	BuryReview(context.Context, *connect.Request[v1.BuryReviewRequest]) (*connect.Response[v1.BuryReviewResponse], error)
	PreviewSRS(context.Context, *connect.Request[v1.PreviewSRSRequest]) (*connect.Response[v1.ReportPayload], error)
	ReportHSK(context.Context, *connect.Request[v1.ReportHSKRequest]) (*connect.Response[v1.ReportPayload], error)
	ReportMastery(context.Context, *connect.Request[v1.ReportMasteryRequest]) (*connect.Response[v1.ReportPayload], error)
	ReportDue(context.Context, *connect.Request[v1.ReportDueRequest]) (*connect.Response[v1.ReportPayload], error)
	SynthesizeSpeech(context.Context, *connect.Request[v1.SynthesizeSpeechRequest]) (*connect.Response[v1.SynthesizeSpeechResponse], error)
	ProcessVoice(context.Context, *connect.Request[v1.ProcessVoiceRequest]) (*connect.Response[v1.ProcessVoiceResponse], error)
	PutContent(context.Context, *connect.Request[v1.PutContentRequest]) (*connect.Response[v1.ContentRecord], error)
	GetContent(context.Context, *connect.Request[v1.GetContentRequest]) (*connect.Response[v1.GetContentResponse], error)
	LogEvent(context.Context, *connect.Request[v1.LogEventRequest]) (*connect.Response[v1.EventRecord], error)
	ListEvents(context.Context, *connect.Request[v1.ListEventsRequest]) (*connect.Response[v1.ListEventsResponse], error)
	Doctor(context.Context, *connect.Request[v1.DoctorRequest]) (*connect.Response[v1.DoctorResponse], error)
}

// NewXuezhServiceClient constructs a client for the xuezh.v1.XuezhService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewXuezhServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) XuezhServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	xuezhServiceMethods := v1.File_xuezh_v1_xuezh_proto.Services().ByName("XuezhService").Methods()
	return &xuezhServiceClient{
		getLearnerState: connect.NewClient[v1.GetLearnerStateRequest, v1.LearnerState](
			httpClient,
			baseURL+XuezhServiceGetLearnerStateProcedure,
			connect.WithSchema(xuezhServiceMethods.ByName("GetLearnerState")),
			connect.WithClientOptions(opts...),
		),
		getSnapshot: connect.NewClient[v1.GetSnapshotRequest, v1.ReportPayload](
			httpClient,
			baseURL+XuezhServiceGetSnapshotProcedure,
			connect.WithSchema(xuezhServiceMethods.ByName("GetSnapshot")),
			connect.WithClientOptions(opts...),
		),
		startReview: connect.NewClient[v1.StartReviewRequest, v1.StartReviewResponse](
			httpClient,
			baseURL+XuezhServiceStartReviewProcedure,
			connect.WithSchema(xuezhServiceMethods.ByName("StartReview")),
			connect.WithClientOptions(opts...),
		),
		gradeReview: connect.NewClient[v1.GradeReviewRequest, v1.GradeReviewResponse](
			httpClient,
			baseURL+XuezhServiceGradeReviewProcedure,
			connect.WithSchema(xuezhServiceMethods.ByName("GradeReview")),
			connect.WithClientOptions(opts...),
		),
		buryReview: connect.NewClient[v1.BuryReviewRequest, v1.BuryReviewResponse](
			httpClient,
			baseURL+XuezhServiceBuryReviewProcedure,
			connect.WithSchema(xuezhServiceMethods.ByName("BuryReview")),
			connect.WithClientOptions(opts...),
		),
		previewSRS: connect.NewClient[v1.PreviewSRSRequest, v1.ReportPayload](
			httpClient,
			baseURL+XuezhServicePreviewSRSProcedure,
			connect.WithSchema(xuezhServiceMethods.ByName("PreviewSRS")),
			connect.WithClientOptions(opts...),
		),
		reportHSK: connect.NewClient[v1.ReportHSKRequest, v1.ReportPayload](
			httpClient,
			baseURL+XuezhServiceReportHSKProcedure,
			connect.WithSchema(xuezhServiceMethods.ByName("ReportHSK")),
			connect.WithClientOptions(opts...),
		),
		reportMastery: connect.NewClient[v1.ReportMasteryRequest, v1.ReportPayload](
			httpClient,
			baseURL+XuezhServiceReportMasteryProcedure,
			connect.WithSchema(xuezhServiceMethods.ByName("ReportMastery")),
			connect.WithClientOptions(opts...),
		),
		reportDue: connect.NewClient[v1.ReportDueRequest, v1.ReportPayload](
			httpClient,
			baseURL+XuezhServiceReportDueProcedure,
			connect.WithSchema(xuezhServiceMethods.ByName("ReportDue")),
			connect.WithClientOptions(opts...),
		),
		synthesizeSpeech: connect.NewClient[v1.SynthesizeSpeechRequest, v1.SynthesizeSpeechResponse](
			httpClient,
			baseURL+XuezhServiceSynthesizeSpeechProcedure,
			connect.WithSchema(xuezhServiceMethods.ByName("SynthesizeSpeech")),
			connect.WithClientOptions(opts...),
		),
		processVoice: connect.NewClient[v1.ProcessVoiceRequest, v1.ProcessVoiceResponse](
			httpClient,
			baseURL+XuezhServiceProcessVoiceProcedure,
			connect.WithSchema(xuezhServiceMethods.ByName("ProcessVoice")),
			connect.WithClientOptions(opts...),
		),
		putContent: connect.NewClient[v1.PutContentRequest, v1.ContentRecord](
			httpClient,
			baseURL+XuezhServicePutContentProcedure,
			connect.WithSchema(xuezhServiceMethods.ByName("PutContent")),
			connect.WithClientOptions(opts...),
		),
		getContent: connect.NewClient[v1.GetContentRequest, v1.GetContentResponse](
			httpClient,
			baseURL+XuezhServiceGetContentProcedure,
			connect.WithSchema(xuezhServiceMethods.ByName("GetContent")),
			connect.WithClientOptions(opts...),
		),
		logEvent: connect.NewClient[v1.LogEventRequest, v1.EventRecord](
			httpClient,
			baseURL+XuezhServiceLogEventProcedure,
			connect.WithSchema(xuezhServiceMethods.ByName("LogEvent")),
			connect.WithClientOptions(opts...),
		),
		listEvents: connect.NewClient[v1.ListEventsRequest, v1.ListEventsResponse](
			httpClient,
			baseURL+XuezhServiceListEventsProcedure,
			connect.WithSchema(xuezhServiceMethods.ByName("ListEvents")),
			connect.WithClientOptions(opts...),
		),
		doctor: connect.NewClient[v1.DoctorRequest, v1.DoctorResponse](
			httpClient,
			baseURL+XuezhServiceDoctorProcedure,
			connect.WithSchema(xuezhServiceMethods.ByName("Doctor")),
			connect.WithClientOptions(opts...),
		),
	}
}

// xuezhServiceClient implements XuezhServiceClient.
type xuezhServiceClient struct {
	getLearnerState  *connect.Client[v1.GetLearnerStateRequest, v1.LearnerState]
	getSnapshot      *connect.Client[v1.GetSnapshotRequest, v1.ReportPayload]
	startReview      *connect.Client[v1.StartReviewRequest, v1.StartReviewResponse]
	gradeReview      *connect.Client[v1.GradeReviewRequest, v1.GradeReviewResponse]
	buryReview       *connect.Client[v1.BuryReviewRequest, v1.BuryReviewResponse]
	previewSRS       *connect.Client[v1.PreviewSRSRequest, v1.ReportPayload]
	reportHSK        *connect.Client[v1.ReportHSKRequest, v1.ReportPayload]
	reportMastery    *connect.Client[v1.ReportMasteryRequest, v1.ReportPayload]
	reportDue        *connect.Client[v1.ReportDueRequest, v1.ReportPayload]
	synthesizeSpeech *connect.Client[v1.SynthesizeSpeechRequest, v1.SynthesizeSpeechResponse]
	processVoice     *connect.Client[v1.ProcessVoiceRequest, v1.ProcessVoiceResponse]
	putContent       *connect.Client[v1.PutContentRequest, v1.ContentRecord]
	getContent       *connect.Client[v1.GetContentRequest, v1.GetContentResponse]
	logEvent         *connect.Client[v1.LogEventRequest, v1.EventRecord]
	listEvents       *connect.Client[v1.ListEventsRequest, v1.ListEventsResponse]
	doctor           *connect.Client[v1.DoctorRequest, v1.DoctorResponse]
}

// GetLearnerState calls xuezh.v1.XuezhService.GetLearnerState.
func (c *xuezhServiceClient) GetLearnerState(ctx context.Context, req *connect.Request[v1.GetLearnerStateRequest]) (*connect.Response[v1.LearnerState], error) {
	return c.getLearnerState.CallUnary(ctx, req)
}

// GetSnapshot calls xuezh.v1.XuezhService.GetSnapshot.
func (c *xuezhServiceClient) GetSnapshot(ctx context.Context, req *connect.Request[v1.GetSnapshotRequest]) (*connect.Response[v1.ReportPayload], error) {
	return c.getSnapshot.CallUnary(ctx, req)
}

// StartReview calls xuezh.v1.XuezhService.StartReview.
func (c *xuezhServiceClient) StartReview(ctx context.Context, req *connect.Request[v1.StartReviewRequest]) (*connect.Response[v1.StartReviewResponse], error) {
	return c.startReview.CallUnary(ctx, req)
}

// GradeReview calls xuezh.v1.XuezhService.GradeReview.
func (c *xuezhServiceClient) GradeReview(ctx context.Context, req *connect.Request[v1.GradeReviewRequest]) (*connect.Response[v1.GradeReviewResponse], error) {
	return c.gradeReview.CallUnary(ctx, req)
}

// BuryReview calls xuezh.v1.XuezhService.BuryReview.
func (c *xuezhServiceClient) BuryReview(ctx context.Context, req *connect.Request[v1.BuryReviewRequest]) (*connect.Response[v1.BuryReviewResponse], error) {
	return c.buryReview.CallUnary(ctx, req)
}

// PreviewSRS calls xuezh.v1.XuezhService.PreviewSRS.
func (c *xuezhServiceClient) PreviewSRS(ctx context.Context, req *connect.Request[v1.PreviewSRSRequest]) (*connect.Response[v1.ReportPayload], error) {
	return c.previewSRS.CallUnary(ctx, req)
}

// ReportHSK calls xuezh.v1.XuezhService.ReportHSK.
func (c *xuezhServiceClient) ReportHSK(ctx context.Context, req *connect.Request[v1.ReportHSKRequest]) (*connect.Response[v1.ReportPayload], error) {
	return c.reportHSK.CallUnary(ctx, req)
}

// ReportMastery calls xuezh.v1.XuezhService.ReportMastery.
func (c *xuezhServiceClient) ReportMastery(ctx context.Context, req *connect.Request[v1.ReportMasteryRequest]) (*connect.Response[v1.ReportPayload], error) {
	return c.reportMastery.CallUnary(ctx, req)
}

// ReportDue calls xuezh.v1.XuezhService.ReportDue.
func (c *xuezhServiceClient) ReportDue(ctx context.Context, req *connect.Request[v1.ReportDueRequest]) (*connect.Response[v1.ReportPayload], error) {
	return c.reportDue.CallUnary(ctx, req)
}

// SynthesizeSpeech calls xuezh.v1.XuezhService.SynthesizeSpeech.
func (c *xuezhServiceClient) SynthesizeSpeech(ctx context.Context, req *connect.Request[v1.SynthesizeSpeechRequest]) (*connect.Response[v1.SynthesizeSpeechResponse], error) {
	return c.synthesizeSpeech.CallUnary(ctx, req)
}

// ProcessVoice calls xuezh.v1.XuezhService.ProcessVoice.
func (c *xuezhServiceClient) ProcessVoice(ctx context.Context, req *connect.Request[v1.ProcessVoiceRequest]) (*connect.Response[v1.ProcessVoiceResponse], error) {
	return c.processVoice.CallUnary(ctx, req)
}

// PutContent calls xuezh.v1.XuezhService.PutContent.
func (c *xuezhServiceClient) PutContent(ctx context.Context, req *connect.Request[v1.PutContentRequest]) (*connect.Response[v1.ContentRecord], error) {
	return c.putContent.CallUnary(ctx, req)
}

// GetContent calls xuezh.v1.XuezhService.GetContent.
func (c *xuezhServiceClient) GetContent(ctx context.Context, req *connect.Request[v1.GetContentRequest]) (*connect.Response[v1.GetContentResponse], error) {
	return c.getContent.CallUnary(ctx, req)
}

// LogEvent calls xuezh.v1.XuezhService.LogEvent.
func (c *xuezhServiceClient) LogEvent(ctx context.Context, req *connect.Request[v1.LogEventRequest]) (*connect.Response[v1.EventRecord], error) {
	return c.logEvent.CallUnary(ctx, req)
}

// ListEvents calls xuezh.v1.XuezhService.ListEvents.
func (c *xuezhServiceClient) ListEvents(ctx context.Context, req *connect.Request[v1.ListEventsRequest]) (*connect.Response[v1.ListEventsResponse], error) {
	return c.listEvents.CallUnary(ctx, req)
}

// Doctor calls xuezh.v1.XuezhService.Doctor.
func (c *xuezhServiceClient) Doctor(ctx context.Context, req *connect.Request[v1.DoctorRequest]) (*connect.Response[v1.DoctorResponse], error) {
	return c.doctor.CallUnary(ctx, req)
}

// XuezhServiceHandler is an implementation of the xuezh.v1.XuezhService service.
type XuezhServiceHandler interface {
	GetLearnerState(context.Context, *connect.Request[v1.GetLearnerStateRequest]) (*connect.Response[v1.LearnerState], error)
	GetSnapshot(context.Context, *connect.Request[v1.GetSnapshotRequest]) (*connect.Response[v1.ReportPayload], error)
	StartReview(context.Context, *connect.Request[v1.StartReviewRequest]) (*connect.Response[v1.StartReviewResponse], error)
	GradeReview(context.Context, *connect.Request[v1.GradeReviewRequest]) (*connect.Response[v1.GradeReviewResponse], error)
	BuryReview(context.Context, *connect.Request[v1.BuryReviewRequest]) (*connect.Response[v1.BuryReviewResponse], error)
	PreviewSRS(context.Context, *connect.Request[v1.PreviewSRSRequest]) (*connect.Response[v1.ReportPayload], error)
	ReportHSK(context.Context, *connect.Request[v1.ReportHSKRequest]) (*connect.Response[v1.ReportPayload], error)
	ReportMastery(context.Context, *connect.Request[v1.ReportMasteryRequest]) (*connect.Response[v1.ReportPayload], error)
	ReportDue(context.Context, *connect.Request[v1.ReportDueRequest]) (*connect.Response[v1.ReportPayload], error)
	SynthesizeSpeech(context.Context, *connect.Request[v1.SynthesizeSpeechRequest]) (*connect.Response[v1.SynthesizeSpeechResponse], error)
	ProcessVoice(context.Context, *connect.Request[v1.ProcessVoiceRequest]) (*connect.Response[v1.ProcessVoiceResponse], error)
	PutContent(context.Context, *connect.Request[v1.PutContentRequest]) (*connect.Response[v1.ContentRecord], error)
	GetContent(context.Context, *connect.Request[v1.GetContentRequest]) (*connect.Response[v1.GetContentResponse], error)
	LogEvent(context.Context, *connect.Request[v1.LogEventRequest]) (*connect.Response[v1.EventRecord], error)
	ListEvents(context.Context, *connect.Request[v1.ListEventsRequest]) (*connect.Response[v1.ListEventsResponse], error)
	Doctor(context.Context, *connect.Request[v1.DoctorRequest]) (*connect.Response[v1.DoctorResponse], error)
}

// NewXuezhServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewXuezhServiceHandler(svc XuezhServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	xuezhServiceMethods := v1.File_xuezh_v1_xuezh_proto.Services().ByName("XuezhService").Methods()
	xuezhServiceGetLearnerStateHandler := connect.NewUnaryHandler(
		XuezhServiceGetLearnerStateProcedure,
		svc.GetLearnerState,
		connect.WithSchema(xuezhServiceMethods.ByName("GetLearnerState")),
		connect.WithHandlerOptions(opts...),
	)
	xuezhServiceGetSnapshotHandler := connect.NewUnaryHandler(
		XuezhServiceGetSnapshotProcedure,
		svc.GetSnapshot,
		connect.WithSchema(xuezhServiceMethods.ByName("GetSnapshot")),
		connect.WithHandlerOptions(opts...),
	)
	xuezhServiceStartReviewHandler := connect.NewUnaryHandler(
		XuezhServiceStartReviewProcedure,
		svc.StartReview,
		connect.WithSchema(xuezhServiceMethods.ByName("StartReview")),
		connect.WithHandlerOptions(opts...),
	)
	xuezhServiceGradeReviewHandler := connect.NewUnaryHandler(
		XuezhServiceGradeReviewProcedure,
		svc.GradeReview,
		connect.WithSchema(xuezhServiceMethods.ByName("GradeReview")),
		connect.WithHandlerOptions(opts...),
	)
	xuezhServiceBuryReviewHandler := connect.NewUnaryHandler(
		XuezhServiceBuryReviewProcedure,
		svc.BuryReview,
		connect.WithSchema(xuezhServiceMethods.ByName("BuryReview")),
		connect.WithHandlerOptions(opts...),
	)
	xuezhServicePreviewSRSHandler := connect.NewUnaryHandler(
		XuezhServicePreviewSRSProcedure,
		svc.PreviewSRS,
		connect.WithSchema(xuezhServiceMethods.ByName("PreviewSRS")),
		connect.WithHandlerOptions(opts...),
	)
	xuezhServiceReportHSKHandler := connect.NewUnaryHandler(
		XuezhServiceReportHSKProcedure,
		svc.ReportHSK,
		connect.WithSchema(xuezhServiceMethods.ByName("ReportHSK")),
		connect.WithHandlerOptions(opts...),
	)
	xuezhServiceReportMasteryHandler := connect.NewUnaryHandler(
		XuezhServiceReportMasteryProcedure,
		svc.ReportMastery,
		connect.WithSchema(xuezhServiceMethods.ByName("ReportMastery")),
		connect.WithHandlerOptions(opts...),
	)
	xuezhServiceReportDueHandler := connect.NewUnaryHandler(
		XuezhServiceReportDueProcedure,
		svc.ReportDue,
		connect.WithSchema(xuezhServiceMethods.ByName("ReportDue")),
		connect.WithHandlerOptions(opts...),
	)
	xuezhServiceSynthesizeSpeechHandler := connect.NewUnaryHandler(
		XuezhServiceSynthesizeSpeechProcedure,
		svc.SynthesizeSpeech,
		connect.WithSchema(xuezhServiceMethods.ByName("SynthesizeSpeech")),
		connect.WithHandlerOptions(opts...),
	)
	xuezhServiceProcessVoiceHandler := connect.NewUnaryHandler(
		XuezhServiceProcessVoiceProcedure,
		svc.ProcessVoice,
		connect.WithSchema(xuezhServiceMethods.ByName("ProcessVoice")),
		connect.WithHandlerOptions(opts...),
	)
	xuezhServicePutContentHandler := connect.NewUnaryHandler(
		XuezhServicePutContentProcedure,
		svc.PutContent,
		connect.WithSchema(xuezhServiceMethods.ByName("PutContent")),
		connect.WithHandlerOptions(opts...),
	)
	xuezhServiceGetContentHandler := connect.NewUnaryHandler(
		XuezhServiceGetContentProcedure,
		svc.GetContent,
		connect.WithSchema(xuezhServiceMethods.ByName("GetContent")),
		connect.WithHandlerOptions(opts...),
	)
	xuezhServiceLogEventHandler := connect.NewUnaryHandler(
		XuezhServiceLogEventProcedure,
		svc.LogEvent,
		connect.WithSchema(xuezhServiceMethods.ByName("LogEvent")),
		connect.WithHandlerOptions(opts...),
	)
	xuezhServiceListEventsHandler := connect.NewUnaryHandler(
		XuezhServiceListEventsProcedure,
		svc.ListEvents,
		connect.WithSchema(xuezhServiceMethods.ByName("ListEvents")),
		connect.WithHandlerOptions(opts...),
	)
	xuezhServiceDoctorHandler := connect.NewUnaryHandler(
		XuezhServiceDoctorProcedure,
		svc.Doctor,
		connect.WithSchema(xuezhServiceMethods.ByName("Doctor")),
		connect.WithHandlerOptions(opts...),
	)
	return "/xuezh.v1.XuezhService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case XuezhServiceGetLearnerStateProcedure:
			xuezhServiceGetLearnerStateHandler.ServeHTTP(w, r)
		case XuezhServiceGetSnapshotProcedure:
			xuezhServiceGetSnapshotHandler.ServeHTTP(w, r)
		case XuezhServiceStartReviewProcedure:
			xuezhServiceStartReviewHandler.ServeHTTP(w, r)
		case XuezhServiceGradeReviewProcedure:
			xuezhServiceGradeReviewHandler.ServeHTTP(w, r)
		case XuezhServiceBuryReviewProcedure:
			xuezhServiceBuryReviewHandler.ServeHTTP(w, r)
		case XuezhServicePreviewSRSProcedure:
			xuezhServicePreviewSRSHandler.ServeHTTP(w, r)
		case XuezhServiceReportHSKProcedure:
			xuezhServiceReportHSKHandler.ServeHTTP(w, r)
		case XuezhServiceReportMasteryProcedure:
			xuezhServiceReportMasteryHandler.ServeHTTP(w, r)
		case XuezhServiceReportDueProcedure:
			xuezhServiceReportDueHandler.ServeHTTP(w, r)
		case XuezhServiceSynthesizeSpeechProcedure:
			xuezhServiceSynthesizeSpeechHandler.ServeHTTP(w, r)
		case XuezhServiceProcessVoiceProcedure:
			xuezhServiceProcessVoiceHandler.ServeHTTP(w, r)
		case XuezhServicePutContentProcedure:
			xuezhServicePutContentHandler.ServeHTTP(w, r)
		case XuezhServiceGetContentProcedure:
			xuezhServiceGetContentHandler.ServeHTTP(w, r)
		case XuezhServiceLogEventProcedure:
			xuezhServiceLogEventHandler.ServeHTTP(w, r)
		case XuezhServiceListEventsProcedure:
			xuezhServiceListEventsHandler.ServeHTTP(w, r)
		case XuezhServiceDoctorProcedure:
			xuezhServiceDoctorHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedXuezhServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedXuezhServiceHandler struct{}

func (UnimplementedXuezhServiceHandler) GetLearnerState(context.Context, *connect.Request[v1.GetLearnerStateRequest]) (*connect.Response[v1.LearnerState], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xuezh.v1.XuezhService.GetLearnerState is not implemented"))
}

func (UnimplementedXuezhServiceHandler) GetSnapshot(context.Context, *connect.Request[v1.GetSnapshotRequest]) (*connect.Response[v1.ReportPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xuezh.v1.XuezhService.GetSnapshot is not implemented"))
}

func (UnimplementedXuezhServiceHandler) StartReview(context.Context, *connect.Request[v1.StartReviewRequest]) (*connect.Response[v1.StartReviewResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xuezh.v1.XuezhService.StartReview is not implemented"))
}

func (UnimplementedXuezhServiceHandler) GradeReview(context.Context, *connect.Request[v1.GradeReviewRequest]) (*connect.Response[v1.GradeReviewResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xuezh.v1.XuezhService.GradeReview is not implemented"))
}

func (UnimplementedXuezhServiceHandler) BuryReview(context.Context, *connect.Request[v1.BuryReviewRequest]) (*connect.Response[v1.BuryReviewResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xuezh.v1.XuezhService.BuryReview is not implemented"))
}

func (UnimplementedXuezhServiceHandler) PreviewSRS(context.Context, *connect.Request[v1.PreviewSRSRequest]) (*connect.Response[v1.ReportPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xuezh.v1.XuezhService.PreviewSRS is not implemented"))
}

func (UnimplementedXuezhServiceHandler) ReportHSK(context.Context, *connect.Request[v1.ReportHSKRequest]) (*connect.Response[v1.ReportPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xuezh.v1.XuezhService.ReportHSK is not implemented"))
}

func (UnimplementedXuezhServiceHandler) ReportMastery(context.Context, *connect.Request[v1.ReportMasteryRequest]) (*connect.Response[v1.ReportPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xuezh.v1.XuezhService.ReportMastery is not implemented"))
}

func (UnimplementedXuezhServiceHandler) ReportDue(context.Context, *connect.Request[v1.ReportDueRequest]) (*connect.Response[v1.ReportPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xuezh.v1.XuezhService.ReportDue is not implemented"))
}

func (UnimplementedXuezhServiceHandler) SynthesizeSpeech(context.Context, *connect.Request[v1.SynthesizeSpeechRequest]) (*connect.Response[v1.SynthesizeSpeechResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xuezh.v1.XuezhService.SynthesizeSpeech is not implemented"))
}

func (UnimplementedXuezhServiceHandler) ProcessVoice(context.Context, *connect.Request[v1.ProcessVoiceRequest]) (*connect.Response[v1.ProcessVoiceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xuezh.v1.XuezhService.ProcessVoice is not implemented"))
}

func (UnimplementedXuezhServiceHandler) PutContent(context.Context, *connect.Request[v1.PutContentRequest]) (*connect.Response[v1.ContentRecord], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xuezh.v1.XuezhService.PutContent is not implemented"))
}

func (UnimplementedXuezhServiceHandler) GetContent(context.Context, *connect.Request[v1.GetContentRequest]) (*connect.Response[v1.GetContentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xuezh.v1.XuezhService.GetContent is not implemented"))
}

func (UnimplementedXuezhServiceHandler) LogEvent(context.Context, *connect.Request[v1.LogEventRequest]) (*connect.Response[v1.EventRecord], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xuezh.v1.XuezhService.LogEvent is not implemented"))
}

func (UnimplementedXuezhServiceHandler) ListEvents(context.Context, *connect.Request[v1.ListEventsRequest]) (*connect.Response[v1.ListEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xuezh.v1.XuezhService.ListEvents is not implemented"))
}

func (UnimplementedXuezhServiceHandler) Doctor(context.Context, *connect.Request[v1.DoctorRequest]) (*connect.Response[v1.DoctorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xuezh.v1.XuezhService.Doctor is not implemented"))
}
