// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: xuezh/v1/xuezh.proto

package xuezhv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerArtifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mime          string                 `protobuf:"bytes,2,opt,name=mime,proto3" json:"mime,omitempty"`
	Purpose       string                 `protobuf:"bytes,3,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Bytes         *int64                 `protobuf:"varint,4,opt,name=bytes,proto3,oneof" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerArtifact) Reset() {
	*x = ServerArtifact{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerArtifact) ProtoMessage() {}

func (x *ServerArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerArtifact.ProtoReflect.Descriptor instead.
func (*ServerArtifact) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{0}
}

func (x *ServerArtifact) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ServerArtifact) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *ServerArtifact) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *ServerArtifact) GetBytes() int64 {
	if x != nil && x.Bytes != nil {
		return *x.Bytes
	}
	return 0
}

type InlineFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Mime          string                 `protobuf:"bytes,2,opt,name=mime,proto3" json:"mime,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InlineFile) Reset() {
	*x = InlineFile{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InlineFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InlineFile) ProtoMessage() {}

func (x *InlineFile) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InlineFile.ProtoReflect.Descriptor instead.
func (*InlineFile) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{1}
}

func (x *InlineFile) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InlineFile) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *InlineFile) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type BackendInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Features      []string               `protobuf:"bytes,2,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendInfo) Reset() {
	*x = BackendInfo{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendInfo) ProtoMessage() {}

func (x *BackendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendInfo.ProtoReflect.Descriptor instead.
func (*BackendInfo) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{2}
}

func (x *BackendInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BackendInfo) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

type ReportPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *structpb.Struct       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Artifacts     []*ServerArtifact      `protobuf:"bytes,2,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	Truncated     bool                   `protobuf:"varint,3,opt,name=truncated,proto3" json:"truncated,omitempty"`
	Limits        *structpb.Struct       `protobuf:"bytes,4,opt,name=limits,proto3" json:"limits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportPayload) Reset() {
	*x = ReportPayload{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportPayload) ProtoMessage() {}

func (x *ReportPayload) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportPayload.ProtoReflect.Descriptor instead.
func (*ReportPayload) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{3}
}

func (x *ReportPayload) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReportPayload) GetArtifacts() []*ServerArtifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *ReportPayload) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *ReportPayload) GetLimits() *structpb.Struct {
	if x != nil {
		return x.Limits
	}
	return nil
}

type GetLearnerStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLearnerStateRequest) Reset() {
	*x = GetLearnerStateRequest{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLearnerStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLearnerStateRequest) ProtoMessage() {}

func (x *GetLearnerStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLearnerStateRequest.ProtoReflect.Descriptor instead.
func (*GetLearnerStateRequest) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{4}
}

type LearnerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	ChangedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=changed_at,json=changedAt,proto3" json:"changed_at,omitempty"`
	StateHash     string                 `protobuf:"bytes,3,opt,name=state_hash,json=stateHash,proto3" json:"state_hash,omitempty"`
	LearnedScore  int32                  `protobuf:"varint,4,opt,name=learned_score,json=learnedScore,proto3" json:"learned_score,omitempty"`
	Columns       []string               `protobuf:"bytes,5,rep,name=columns,proto3" json:"columns,omitempty"`
	Cards         []*LearnerCardRow      `protobuf:"bytes,6,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LearnerState) Reset() {
	*x = LearnerState{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LearnerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearnerState) ProtoMessage() {}

func (x *LearnerState) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearnerState.ProtoReflect.Descriptor instead.
func (*LearnerState) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{5}
}

func (x *LearnerState) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *LearnerState) GetChangedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ChangedAt
	}
	return nil
}

func (x *LearnerState) GetStateHash() string {
	if x != nil {
		return x.StateHash
	}
	return ""
}

func (x *LearnerState) GetLearnedScore() int32 {
	if x != nil {
		return x.LearnedScore
	}
	return 0
}

func (x *LearnerState) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *LearnerState) GetCards() []*LearnerCardRow {
	if x != nil {
		return x.Cards
	}
	return nil
}

type LearnerCardRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*structpb.Value      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LearnerCardRow) Reset() {
	*x = LearnerCardRow{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LearnerCardRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearnerCardRow) ProtoMessage() {}

func (x *LearnerCardRow) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearnerCardRow.ProtoReflect.Descriptor instead.
func (*LearnerCardRow) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{6}
}

func (x *LearnerCardRow) GetValues() []*structpb.Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type GetSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Window        string                 `protobuf:"bytes,1,opt,name=window,proto3" json:"window,omitempty"`
	DueLimit      int32                  `protobuf:"varint,2,opt,name=due_limit,json=dueLimit,proto3" json:"due_limit,omitempty"`
	EvidenceLimit int32                  `protobuf:"varint,3,opt,name=evidence_limit,json=evidenceLimit,proto3" json:"evidence_limit,omitempty"`
	MaxBytes      int32                  `protobuf:"varint,4,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotRequest) Reset() {
	*x = GetSnapshotRequest{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotRequest) ProtoMessage() {}

func (x *GetSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{7}
}

func (x *GetSnapshotRequest) GetWindow() string {
	if x != nil {
		return x.Window
	}
	return ""
}

func (x *GetSnapshotRequest) GetDueLimit() int32 {
	if x != nil {
		return x.DueLimit
	}
	return 0
}

func (x *GetSnapshotRequest) GetEvidenceLimit() int32 {
	if x != nil {
		return x.EvidenceLimit
	}
	return 0
}

func (x *GetSnapshotRequest) GetMaxBytes() int32 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

type StartReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartReviewRequest) Reset() {
	*x = StartReviewRequest{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartReviewRequest) ProtoMessage() {}

func (x *StartReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartReviewRequest.ProtoReflect.Descriptor instead.
func (*StartReviewRequest) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{8}
}

func (x *StartReviewRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ReviewItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	DueAt         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=due_at,json=dueAt,proto3" json:"due_at,omitempty"`
	ReviewType    string                 `protobuf:"bytes,3,opt,name=review_type,json=reviewType,proto3" json:"review_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewItem) Reset() {
	*x = ReviewItem{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewItem) ProtoMessage() {}

func (x *ReviewItem) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewItem.ProtoReflect.Descriptor instead.
func (*ReviewItem) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{9}
}

func (x *ReviewItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ReviewItem) GetDueAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DueAt
	}
	return nil
}

func (x *ReviewItem) GetReviewType() string {
	if x != nil {
		return x.ReviewType
	}
	return ""
}

type StartReviewResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RecallItems        []*ReviewItem          `protobuf:"bytes,1,rep,name=recall_items,json=recallItems,proto3" json:"recall_items,omitempty"`
	PronunciationItems []*ReviewItem          `protobuf:"bytes,2,rep,name=pronunciation_items,json=pronunciationItems,proto3" json:"pronunciation_items,omitempty"`
	GeneratedAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StartReviewResponse) Reset() {
	*x = StartReviewResponse{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartReviewResponse) ProtoMessage() {}

func (x *StartReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartReviewResponse.ProtoReflect.Descriptor instead.
func (*StartReviewResponse) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{10}
}

func (x *StartReviewResponse) GetRecallItems() []*ReviewItem {
	if x != nil {
		return x.RecallItems
	}
	return nil
}

func (x *StartReviewResponse) GetPronunciationItems() []*ReviewItem {
	if x != nil {
		return x.PronunciationItems
	}
	return nil
}

func (x *StartReviewResponse) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

type GradeReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Recall        *int32                 `protobuf:"varint,2,opt,name=recall,proto3,oneof" json:"recall,omitempty"`
	Pronunciation *int32                 `protobuf:"varint,3,opt,name=pronunciation,proto3,oneof" json:"pronunciation,omitempty"`
	NextDue       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=next_due,json=nextDue,proto3" json:"next_due,omitempty"`
	Rule          string                 `protobuf:"bytes,5,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeReviewRequest) Reset() {
	*x = GradeReviewRequest{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeReviewRequest) ProtoMessage() {}

func (x *GradeReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeReviewRequest.ProtoReflect.Descriptor instead.
func (*GradeReviewRequest) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{11}
}

func (x *GradeReviewRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *GradeReviewRequest) GetRecall() int32 {
	if x != nil && x.Recall != nil {
		return *x.Recall
	}
	return 0
}

func (x *GradeReviewRequest) GetPronunciation() int32 {
	if x != nil && x.Pronunciation != nil {
		return *x.Pronunciation
	}
	return 0
}

func (x *GradeReviewRequest) GetNextDue() *timestamppb.Timestamp {
	if x != nil {
		return x.NextDue
	}
	return nil
}

func (x *GradeReviewRequest) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

type GradeReviewResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ItemId                   string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	RecallGrade              *int32                 `protobuf:"varint,2,opt,name=recall_grade,json=recallGrade,proto3,oneof" json:"recall_grade,omitempty"`
	RecallNextDue            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=recall_next_due,json=recallNextDue,proto3" json:"recall_next_due,omitempty"`
	RecallRuleApplied        *string                `protobuf:"bytes,4,opt,name=recall_rule_applied,json=recallRuleApplied,proto3,oneof" json:"recall_rule_applied,omitempty"`
	PronunciationGrade       *int32                 `protobuf:"varint,5,opt,name=pronunciation_grade,json=pronunciationGrade,proto3,oneof" json:"pronunciation_grade,omitempty"`
	PronunciationNextDue     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=pronunciation_next_due,json=pronunciationNextDue,proto3" json:"pronunciation_next_due,omitempty"`
	PronunciationRuleApplied *string                `protobuf:"bytes,7,opt,name=pronunciation_rule_applied,json=pronunciationRuleApplied,proto3,oneof" json:"pronunciation_rule_applied,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GradeReviewResponse) Reset() {
	*x = GradeReviewResponse{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeReviewResponse) ProtoMessage() {}

func (x *GradeReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeReviewResponse.ProtoReflect.Descriptor instead.
func (*GradeReviewResponse) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{12}
}

func (x *GradeReviewResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *GradeReviewResponse) GetRecallGrade() int32 {
	if x != nil && x.RecallGrade != nil {
		return *x.RecallGrade
	}
	return 0
}

func (x *GradeReviewResponse) GetRecallNextDue() *timestamppb.Timestamp {
	if x != nil {
		return x.RecallNextDue
	}
	return nil
}

func (x *GradeReviewResponse) GetRecallRuleApplied() string {
	if x != nil && x.RecallRuleApplied != nil {
		return *x.RecallRuleApplied
	}
	return ""
}

func (x *GradeReviewResponse) GetPronunciationGrade() int32 {
	if x != nil && x.PronunciationGrade != nil {
		return *x.PronunciationGrade
	}
	return 0
}

func (x *GradeReviewResponse) GetPronunciationNextDue() *timestamppb.Timestamp {
	if x != nil {
		return x.PronunciationNextDue
	}
	return nil
}

func (x *GradeReviewResponse) GetPronunciationRuleApplied() string {
	if x != nil && x.PronunciationRuleApplied != nil {
		return *x.PronunciationRuleApplied
	}
	return ""
}

type BuryReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuryReviewRequest) Reset() {
	*x = BuryReviewRequest{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuryReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuryReviewRequest) ProtoMessage() {}

func (x *BuryReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuryReviewRequest.ProtoReflect.Descriptor instead.
func (*BuryReviewRequest) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{13}
}

func (x *BuryReviewRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *BuryReviewRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type BuryReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	NextDue       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=next_due,json=nextDue,proto3" json:"next_due,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuryReviewResponse) Reset() {
	*x = BuryReviewResponse{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuryReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuryReviewResponse) ProtoMessage() {}

func (x *BuryReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuryReviewResponse.ProtoReflect.Descriptor instead.
func (*BuryReviewResponse) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{14}
}

func (x *BuryReviewResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *BuryReviewResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BuryReviewResponse) GetNextDue() *timestamppb.Timestamp {
	if x != nil {
		return x.NextDue
	}
	return nil
}

type PreviewSRSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          int32                  `protobuf:"varint,1,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewSRSRequest) Reset() {
	*x = PreviewSRSRequest{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewSRSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewSRSRequest) ProtoMessage() {}

func (x *PreviewSRSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewSRSRequest.ProtoReflect.Descriptor instead.
func (*PreviewSRSRequest) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{15}
}

func (x *PreviewSRSRequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type ReportHSKRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Window        string                 `protobuf:"bytes,2,opt,name=window,proto3" json:"window,omitempty"`
	MaxItems      int32                  `protobuf:"varint,3,opt,name=max_items,json=maxItems,proto3" json:"max_items,omitempty"`
	MaxBytes      int32                  `protobuf:"varint,4,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	IncludeChars  bool                   `protobuf:"varint,5,opt,name=include_chars,json=includeChars,proto3" json:"include_chars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportHSKRequest) Reset() {
	*x = ReportHSKRequest{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportHSKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportHSKRequest) ProtoMessage() {}

func (x *ReportHSKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportHSKRequest.ProtoReflect.Descriptor instead.
func (*ReportHSKRequest) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{16}
}

func (x *ReportHSKRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *ReportHSKRequest) GetWindow() string {
	if x != nil {
		return x.Window
	}
	return ""
}

func (x *ReportHSKRequest) GetMaxItems() int32 {
	if x != nil {
		return x.MaxItems
	}
	return 0
}

func (x *ReportHSKRequest) GetMaxBytes() int32 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

func (x *ReportHSKRequest) GetIncludeChars() bool {
	if x != nil {
		return x.IncludeChars
	}
	return false
}

type ReportMasteryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemType      string                 `protobuf:"bytes,1,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	Window        string                 `protobuf:"bytes,2,opt,name=window,proto3" json:"window,omitempty"`
	MaxItems      int32                  `protobuf:"varint,3,opt,name=max_items,json=maxItems,proto3" json:"max_items,omitempty"`
	MaxBytes      int32                  `protobuf:"varint,4,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportMasteryRequest) Reset() {
	*x = ReportMasteryRequest{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportMasteryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportMasteryRequest) ProtoMessage() {}

func (x *ReportMasteryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportMasteryRequest.ProtoReflect.Descriptor instead.
func (*ReportMasteryRequest) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{17}
}

func (x *ReportMasteryRequest) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *ReportMasteryRequest) GetWindow() string {
	if x != nil {
		return x.Window
	}
	return ""
}

func (x *ReportMasteryRequest) GetMaxItems() int32 {
	if x != nil {
		return x.MaxItems
	}
	return 0
}

func (x *ReportMasteryRequest) GetMaxBytes() int32 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

type ReportDueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	MaxBytes      int32                  `protobuf:"varint,2,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportDueRequest) Reset() {
	*x = ReportDueRequest{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDueRequest) ProtoMessage() {}

func (x *ReportDueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDueRequest.ProtoReflect.Descriptor instead.
func (*ReportDueRequest) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{18}
}

func (x *ReportDueRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ReportDueRequest) GetMaxBytes() int32 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

type SynthesizeSpeechRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Voice         string                 `protobuf:"bytes,2,opt,name=voice,proto3" json:"voice,omitempty"`
	OutputFormat  string                 `protobuf:"bytes,3,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeSpeechRequest) Reset() {
	*x = SynthesizeSpeechRequest{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeSpeechRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeSpeechRequest) ProtoMessage() {}

func (x *SynthesizeSpeechRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeSpeechRequest.ProtoReflect.Descriptor instead.
func (*SynthesizeSpeechRequest) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{19}
}

func (x *SynthesizeSpeechRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SynthesizeSpeechRequest) GetVoice() string {
	if x != nil {
		return x.Voice
	}
	return ""
}

func (x *SynthesizeSpeechRequest) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

type SynthesizeSpeechResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Voice         string                 `protobuf:"bytes,2,opt,name=voice,proto3" json:"voice,omitempty"`
	Backend       *BackendInfo           `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	Artifacts     []*ServerArtifact      `protobuf:"bytes,4,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	Audio         *InlineFile            `protobuf:"bytes,5,opt,name=audio,proto3" json:"audio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeSpeechResponse) Reset() {
	*x = SynthesizeSpeechResponse{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeSpeechResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeSpeechResponse) ProtoMessage() {}

func (x *SynthesizeSpeechResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeSpeechResponse.ProtoReflect.Descriptor instead.
func (*SynthesizeSpeechResponse) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{20}
}

func (x *SynthesizeSpeechResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SynthesizeSpeechResponse) GetVoice() string {
	if x != nil {
		return x.Voice
	}
	return ""
}

func (x *SynthesizeSpeechResponse) GetBackend() *BackendInfo {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *SynthesizeSpeechResponse) GetArtifacts() []*ServerArtifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *SynthesizeSpeechResponse) GetAudio() *InlineFile {
	if x != nil {
		return x.Audio
	}
	return nil
}

type ProcessVoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audio         []byte                 `protobuf:"bytes,1,opt,name=audio,proto3" json:"audio,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Mime          string                 `protobuf:"bytes,3,opt,name=mime,proto3" json:"mime,omitempty"`
	RefText       string                 `protobuf:"bytes,4,opt,name=ref_text,json=refText,proto3" json:"ref_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessVoiceRequest) Reset() {
	*x = ProcessVoiceRequest{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessVoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessVoiceRequest) ProtoMessage() {}

func (x *ProcessVoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessVoiceRequest.ProtoReflect.Descriptor instead.
func (*ProcessVoiceRequest) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{21}
}

func (x *ProcessVoiceRequest) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *ProcessVoiceRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ProcessVoiceRequest) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *ProcessVoiceRequest) GetRefText() string {
	if x != nil {
		return x.RefText
	}
	return ""
}

type ProcessVoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptId     string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	RefText       string                 `protobuf:"bytes,2,opt,name=ref_text,json=refText,proto3" json:"ref_text,omitempty"`
	Backend       *BackendInfo           `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	Assessment    *structpb.Struct       `protobuf:"bytes,4,opt,name=assessment,proto3" json:"assessment,omitempty"`
	Transcript    *structpb.Struct       `protobuf:"bytes,5,opt,name=transcript,proto3" json:"transcript,omitempty"`
	Artifacts     []*ServerArtifact      `protobuf:"bytes,6,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	FeedbackAudio *InlineFile            `protobuf:"bytes,7,opt,name=feedback_audio,json=feedbackAudio,proto3" json:"feedback_audio,omitempty"`
	Truncated     bool                   `protobuf:"varint,8,opt,name=truncated,proto3" json:"truncated,omitempty"`
	Limits        *structpb.Struct       `protobuf:"bytes,9,opt,name=limits,proto3" json:"limits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessVoiceResponse) Reset() {
	*x = ProcessVoiceResponse{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessVoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessVoiceResponse) ProtoMessage() {}

func (x *ProcessVoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessVoiceResponse.ProtoReflect.Descriptor instead.
func (*ProcessVoiceResponse) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{22}
}

func (x *ProcessVoiceResponse) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *ProcessVoiceResponse) GetRefText() string {
	if x != nil {
		return x.RefText
	}
	return ""
}

func (x *ProcessVoiceResponse) GetBackend() *BackendInfo {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *ProcessVoiceResponse) GetAssessment() *structpb.Struct {
	if x != nil {
		return x.Assessment
	}
	return nil
}

func (x *ProcessVoiceResponse) GetTranscript() *structpb.Struct {
	if x != nil {
		return x.Transcript
	}
	return nil
}

func (x *ProcessVoiceResponse) GetArtifacts() []*ServerArtifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *ProcessVoiceResponse) GetFeedbackAudio() *InlineFile {
	if x != nil {
		return x.FeedbackAudio
	}
	return nil
}

func (x *ProcessVoiceResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *ProcessVoiceResponse) GetLimits() *structpb.Struct {
	if x != nil {
		return x.Limits
	}
	return nil
}

type PutContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutContentRequest) Reset() {
	*x = PutContentRequest{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutContentRequest) ProtoMessage() {}

func (x *PutContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutContentRequest.ProtoReflect.Descriptor instead.
func (*PutContentRequest) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{23}
}

func (x *PutContentRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PutContentRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutContentRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *PutContentRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type GetContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentRequest) Reset() {
	*x = GetContentRequest{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentRequest) ProtoMessage() {}

func (x *GetContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentRequest.ProtoReflect.Descriptor instead.
func (*GetContentRequest) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{24}
}

func (x *GetContentRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetContentRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ContentRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	ContentId     string                 `protobuf:"bytes,3,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Artifacts     []*ServerArtifact      `protobuf:"bytes,4,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentRecord) Reset() {
	*x = ContentRecord{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentRecord) ProtoMessage() {}

func (x *ContentRecord) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentRecord.ProtoReflect.Descriptor instead.
func (*ContentRecord) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{25}
}

func (x *ContentRecord) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ContentRecord) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ContentRecord) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *ContentRecord) GetArtifacts() []*ServerArtifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type GetContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *ContentRecord         `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentResponse) Reset() {
	*x = GetContentResponse{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentResponse) ProtoMessage() {}

func (x *GetContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentResponse.ProtoReflect.Descriptor instead.
func (*GetContentResponse) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{26}
}

func (x *GetContentResponse) GetRecord() *ContentRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *GetContentResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type LogEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Modality      string                 `protobuf:"bytes,2,opt,name=modality,proto3" json:"modality,omitempty"`
	Items         []string               `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Context       *string                `protobuf:"bytes,4,opt,name=context,proto3,oneof" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEventRequest) Reset() {
	*x = LogEventRequest{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEventRequest) ProtoMessage() {}

func (x *LogEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEventRequest.ProtoReflect.Descriptor instead.
func (*LogEventRequest) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{27}
}

func (x *LogEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *LogEventRequest) GetModality() string {
	if x != nil {
		return x.Modality
	}
	return ""
}

func (x *LogEventRequest) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *LogEventRequest) GetContext() string {
	if x != nil && x.Context != nil {
		return *x.Context
	}
	return ""
}

type EventRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Modality      string                 `protobuf:"bytes,4,opt,name=modality,proto3" json:"modality,omitempty"`
	Items         []string               `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	Context       *string                `protobuf:"bytes,6,opt,name=context,proto3,oneof" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRecord) Reset() {
	*x = EventRecord{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRecord) ProtoMessage() {}

func (x *EventRecord) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRecord.ProtoReflect.Descriptor instead.
func (*EventRecord) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{28}
}

func (x *EventRecord) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventRecord) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventRecord) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *EventRecord) GetModality() string {
	if x != nil {
		return x.Modality
	}
	return ""
}

func (x *EventRecord) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *EventRecord) GetContext() string {
	if x != nil && x.Context != nil {
		return *x.Context
	}
	return ""
}

type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Since         string                 `protobuf:"bytes,1,opt,name=since,proto3" json:"since,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{29}
}

func (x *ListEventsRequest) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

func (x *ListEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventRecord         `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{30}
}

func (x *ListEventsResponse) GetEvents() []*EventRecord {
	if x != nil {
		return x.Events
	}
	return nil
}

type DoctorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoctorRequest) Reset() {
	*x = DoctorRequest{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoctorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorRequest) ProtoMessage() {}

func (x *DoctorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorRequest.ProtoReflect.Descriptor instead.
func (*DoctorRequest) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{31}
}

type DoctorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerVersion string                 `protobuf:"bytes,1,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	WorkspaceRole string                 `protobuf:"bytes,2,opt,name=workspace_role,json=workspaceRole,proto3" json:"workspace_role,omitempty"`
	WorkspacePath string                 `protobuf:"bytes,3,opt,name=workspace_path,json=workspacePath,proto3" json:"workspace_path,omitempty"`
	Checks        []*DoctorCheck         `protobuf:"bytes,4,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoctorResponse) Reset() {
	*x = DoctorResponse{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoctorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorResponse) ProtoMessage() {}

func (x *DoctorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorResponse.ProtoReflect.Descriptor instead.
func (*DoctorResponse) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{32}
}

func (x *DoctorResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *DoctorResponse) GetWorkspaceRole() string {
	if x != nil {
		return x.WorkspaceRole
	}
	return ""
}

func (x *DoctorResponse) GetWorkspacePath() string {
	if x != nil {
		return x.WorkspacePath
	}
	return ""
}

func (x *DoctorResponse) GetChecks() []*DoctorCheck {
	if x != nil {
		return x.Checks
	}
	return nil
}

type DoctorCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Details       *structpb.Struct       `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoctorCheck) Reset() {
	*x = DoctorCheck{}
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoctorCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorCheck) ProtoMessage() {}

func (x *DoctorCheck) ProtoReflect() protoreflect.Message {
	mi := &file_xuezh_v1_xuezh_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorCheck.ProtoReflect.Descriptor instead.
func (*DoctorCheck) Descriptor() ([]byte, []int) {
	return file_xuezh_v1_xuezh_proto_rawDescGZIP(), []int{33}
}

func (x *DoctorCheck) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DoctorCheck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DoctorCheck) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_xuezh_v1_xuezh_proto protoreflect.FileDescriptor

const file_xuezh_v1_xuezh_proto_rawDesc = "" +
	"\n" +
	"\x14xuezh/v1/xuezh.proto\x12\bxuezh.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"w\n" +
	"\x0eServerArtifact\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mime\x18\x02 \x01(\tR\x04mime\x12\x18\n" +
	"\apurpose\x18\x03 \x01(\tR\apurpose\x12\x19\n" +
	"\x05bytes\x18\x04 \x01(\x03H\x00R\x05bytes\x88\x01\x01B\b\n" +
	"\x06_bytes\"P\n" +
	"\n" +
	"InlineFile\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x12\n" +
	"\x04mime\x18\x02 \x01(\tR\x04mime\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\"9\n" +
	"\vBackendInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfeatures\x18\x02 \x03(\tR\bfeatures\"\xc3\x01\n" +
	"\rReportPayload\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04data\x126\n" +
	"\tartifacts\x18\x02 \x03(\v2\x18.xuezh.v1.ServerArtifactR\tartifacts\x12\x1c\n" +
	"\ttruncated\x18\x03 \x01(\bR\ttruncated\x12/\n" +
	"\x06limits\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06limits\"\x18\n" +
	"\x16GetLearnerStateRequest\"\x96\x02\n" +
	"\fLearnerState\x12=\n" +
	"\fgenerated_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x129\n" +
	"\n" +
	"changed_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tchangedAt\x12\x1d\n" +
	"\n" +
	"state_hash\x18\x03 \x01(\tR\tstateHash\x12#\n" +
	"\rlearned_score\x18\x04 \x01(\x05R\flearnedScore\x12\x18\n" +
	"\acolumns\x18\x05 \x03(\tR\acolumns\x12.\n" +
	"\x05cards\x18\x06 \x03(\v2\x18.xuezh.v1.LearnerCardRowR\x05cards\"@\n" +
	"\x0eLearnerCardRow\x12.\n" +
	"\x06values\x18\x01 \x03(\v2\x16.google.protobuf.ValueR\x06values\"\x8d\x01\n" +
	"\x12GetSnapshotRequest\x12\x16\n" +
	"\x06window\x18\x01 \x01(\tR\x06window\x12\x1b\n" +
	"\tdue_limit\x18\x02 \x01(\x05R\bdueLimit\x12%\n" +
	"\x0eevidence_limit\x18\x03 \x01(\x05R\revidenceLimit\x12\x1b\n" +
	"\tmax_bytes\x18\x04 \x01(\x05R\bmaxBytes\"*\n" +
	"\x12StartReviewRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"y\n" +
	"\n" +
	"ReviewItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x121\n" +
	"\x06due_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05dueAt\x12\x1f\n" +
	"\vreview_type\x18\x03 \x01(\tR\n" +
	"reviewType\"\xd4\x01\n" +
	"\x13StartReviewResponse\x127\n" +
	"\frecall_items\x18\x01 \x03(\v2\x14.xuezh.v1.ReviewItemR\vrecallItems\x12E\n" +
	"\x13pronunciation_items\x18\x02 \x03(\v2\x14.xuezh.v1.ReviewItemR\x12pronunciationItems\x12=\n" +
	"\fgenerated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\"\xdd\x01\n" +
	"\x12GradeReviewRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1b\n" +
	"\x06recall\x18\x02 \x01(\x05H\x00R\x06recall\x88\x01\x01\x12)\n" +
	"\rpronunciation\x18\x03 \x01(\x05H\x01R\rpronunciation\x88\x01\x01\x125\n" +
	"\bnext_due\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\anextDue\x12\x12\n" +
	"\x04rule\x18\x05 \x01(\tR\x04ruleB\t\n" +
	"\a_recallB\x10\n" +
	"\x0e_pronunciation\"\xfa\x03\n" +
	"\x13GradeReviewResponse\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12&\n" +
	"\frecall_grade\x18\x02 \x01(\x05H\x00R\vrecallGrade\x88\x01\x01\x12B\n" +
	"\x0frecall_next_due\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rrecallNextDue\x123\n" +
	"\x13recall_rule_applied\x18\x04 \x01(\tH\x01R\x11recallRuleApplied\x88\x01\x01\x124\n" +
	"\x13pronunciation_grade\x18\x05 \x01(\x05H\x02R\x12pronunciationGrade\x88\x01\x01\x12P\n" +
	"\x16pronunciation_next_due\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x14pronunciationNextDue\x12A\n" +
	"\x1apronunciation_rule_applied\x18\a \x01(\tH\x03R\x18pronunciationRuleApplied\x88\x01\x01B\x0f\n" +
	"\r_recall_gradeB\x16\n" +
	"\x14_recall_rule_appliedB\x16\n" +
	"\x14_pronunciation_gradeB\x1d\n" +
	"\x1b_pronunciation_rule_applied\"D\n" +
	"\x11BuryReviewRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"|\n" +
	"\x12BuryReviewResponse\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x125\n" +
	"\bnext_due\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\anextDue\"'\n" +
	"\x11PreviewSRSRequest\x12\x12\n" +
	"\x04days\x18\x01 \x01(\x05R\x04days\"\x9f\x01\n" +
	"\x10ReportHSKRequest\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x16\n" +
	"\x06window\x18\x02 \x01(\tR\x06window\x12\x1b\n" +
	"\tmax_items\x18\x03 \x01(\x05R\bmaxItems\x12\x1b\n" +
	"\tmax_bytes\x18\x04 \x01(\x05R\bmaxBytes\x12#\n" +
	"\rinclude_chars\x18\x05 \x01(\bR\fincludeChars\"\x85\x01\n" +
	"\x14ReportMasteryRequest\x12\x1b\n" +
	"\titem_type\x18\x01 \x01(\tR\bitemType\x12\x16\n" +
	"\x06window\x18\x02 \x01(\tR\x06window\x12\x1b\n" +
	"\tmax_items\x18\x03 \x01(\x05R\bmaxItems\x12\x1b\n" +
	"\tmax_bytes\x18\x04 \x01(\x05R\bmaxBytes\"E\n" +
	"\x10ReportDueRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x1b\n" +
	"\tmax_bytes\x18\x02 \x01(\x05R\bmaxBytes\"h\n" +
	"\x17SynthesizeSpeechRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05voice\x18\x02 \x01(\tR\x05voice\x12#\n" +
	"\routput_format\x18\x03 \x01(\tR\foutputFormat\"\xd9\x01\n" +
	"\x18SynthesizeSpeechResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05voice\x18\x02 \x01(\tR\x05voice\x12/\n" +
	"\abackend\x18\x03 \x01(\v2\x15.xuezh.v1.BackendInfoR\abackend\x126\n" +
	"\tartifacts\x18\x04 \x03(\v2\x18.xuezh.v1.ServerArtifactR\tartifacts\x12*\n" +
	"\x05audio\x18\x05 \x01(\v2\x14.xuezh.v1.InlineFileR\x05audio\"v\n" +
	"\x13ProcessVoiceRequest\x12\x14\n" +
	"\x05audio\x18\x01 \x01(\fR\x05audio\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x12\n" +
	"\x04mime\x18\x03 \x01(\tR\x04mime\x12\x19\n" +
	"\bref_text\x18\x04 \x01(\tR\arefText\"\xb7\x03\n" +
	"\x14ProcessVoiceResponse\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12\x19\n" +
	"\bref_text\x18\x02 \x01(\tR\arefText\x12/\n" +
	"\abackend\x18\x03 \x01(\v2\x15.xuezh.v1.BackendInfoR\abackend\x127\n" +
	"\n" +
	"assessment\x18\x04 \x01(\v2\x17.google.protobuf.StructR\n" +
	"assessment\x127\n" +
	"\n" +
	"transcript\x18\x05 \x01(\v2\x17.google.protobuf.StructR\n" +
	"transcript\x126\n" +
	"\tartifacts\x18\x06 \x03(\v2\x18.xuezh.v1.ServerArtifactR\tartifacts\x12;\n" +
	"\x0efeedback_audio\x18\a \x01(\v2\x14.xuezh.v1.InlineFileR\rfeedbackAudio\x12\x1c\n" +
	"\ttruncated\x18\b \x01(\bR\ttruncated\x12/\n" +
	"\x06limits\x18\t \x01(\v2\x17.google.protobuf.StructR\x06limits\"o\n" +
	"\x11PutContentRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\"9\n" +
	"\x11GetContentRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\x8c\x01\n" +
	"\rContentRecord\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"content_id\x18\x03 \x01(\tR\tcontentId\x126\n" +
	"\tartifacts\x18\x04 \x03(\v2\x18.xuezh.v1.ServerArtifactR\tartifacts\"_\n" +
	"\x12GetContentResponse\x12/\n" +
	"\x06record\x18\x01 \x01(\v2\x17.xuezh.v1.ContentRecordR\x06record\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"\x8d\x01\n" +
	"\x0fLogEventRequest\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1a\n" +
	"\bmodality\x18\x02 \x01(\tR\bmodality\x12\x14\n" +
	"\x05items\x18\x03 \x03(\tR\x05items\x12\x1d\n" +
	"\acontext\x18\x04 \x01(\tH\x00R\acontext\x88\x01\x01B\n" +
	"\n" +
	"\b_context\"\xd0\x01\n" +
	"\vEventRecord\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12*\n" +
	"\x02ts\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x1a\n" +
	"\bmodality\x18\x04 \x01(\tR\bmodality\x12\x14\n" +
	"\x05items\x18\x05 \x03(\tR\x05items\x12\x1d\n" +
	"\acontext\x18\x06 \x01(\tH\x00R\acontext\x88\x01\x01B\n" +
	"\n" +
	"\b_context\"?\n" +
	"\x11ListEventsRequest\x12\x14\n" +
	"\x05since\x18\x01 \x01(\tR\x05since\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"C\n" +
	"\x12ListEventsResponse\x12-\n" +
	"\x06events\x18\x01 \x03(\v2\x15.xuezh.v1.EventRecordR\x06events\"\x0f\n" +
	"\rDoctorRequest\"\xb4\x01\n" +
	"\x0eDoctorResponse\x12%\n" +
	"\x0eserver_version\x18\x01 \x01(\tR\rserverVersion\x12%\n" +
	"\x0eworkspace_role\x18\x02 \x01(\tR\rworkspaceRole\x12%\n" +
	"\x0eworkspace_path\x18\x03 \x01(\tR\rworkspacePath\x12-\n" +
	"\x06checks\x18\x04 \x03(\v2\x15.xuezh.v1.DoctorCheckR\x06checks\"d\n" +
	"\vDoctorCheck\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x121\n" +
	"\adetails\x18\x03 \x01(\v2\x17.google.protobuf.StructR\adetails2\x8f\t\n" +
	"\fXuezhService\x12K\n" +
	"\x0fGetLearnerState\x12 .xuezh.v1.GetLearnerStateRequest\x1a\x16.xuezh.v1.LearnerState\x12D\n" +
	"\vGetSnapshot\x12\x1c.xuezh.v1.GetSnapshotRequest\x1a\x17.xuezh.v1.ReportPayload\x12J\n" +
	"\vStartReview\x12\x1c.xuezh.v1.StartReviewRequest\x1a\x1d.xuezh.v1.StartReviewResponse\x12J\n" +
	"\vGradeReview\x12\x1c.xuezh.v1.GradeReviewRequest\x1a\x1d.xuezh.v1.GradeReviewResponse\x12G\n" +
	"\n" +
	"BuryReview\x12\x1b.xuezh.v1.BuryReviewRequest\x1a\x1c.xuezh.v1.BuryReviewResponse\x12B\n" +
	"\n" +
	"PreviewSRS\x12\x1b.xuezh.v1.PreviewSRSRequest\x1a\x17.xuezh.v1.ReportPayload\x12@\n" +
	"\tReportHSK\x12\x1a.xuezh.v1.ReportHSKRequest\x1a\x17.xuezh.v1.ReportPayload\x12H\n" +
	"\rReportMastery\x12\x1e.xuezh.v1.ReportMasteryRequest\x1a\x17.xuezh.v1.ReportPayload\x12@\n" +
	"\tReportDue\x12\x1a.xuezh.v1.ReportDueRequest\x1a\x17.xuezh.v1.ReportPayload\x12Y\n" +
	"\x10SynthesizeSpeech\x12!.xuezh.v1.SynthesizeSpeechRequest\x1a\".xuezh.v1.SynthesizeSpeechResponse\x12M\n" +
	"\fProcessVoice\x12\x1d.xuezh.v1.ProcessVoiceRequest\x1a\x1e.xuezh.v1.ProcessVoiceResponse\x12B\n" +
	"\n" +
	"PutContent\x12\x1b.xuezh.v1.PutContentRequest\x1a\x17.xuezh.v1.ContentRecord\x12G\n" +
	"\n" +
	"GetContent\x12\x1b.xuezh.v1.GetContentRequest\x1a\x1c.xuezh.v1.GetContentResponse\x12<\n" +
	"\bLogEvent\x12\x19.xuezh.v1.LogEventRequest\x1a\x15.xuezh.v1.EventRecord\x12G\n" +
	"\n" +
	"ListEvents\x12\x1b.xuezh.v1.ListEventsRequest\x1a\x1c.xuezh.v1.ListEventsResponse\x12;\n" +
	"\x06Doctor\x12\x17.xuezh.v1.DoctorRequest\x1a\x18.xuezh.v1.DoctorResponseB0Z.github.com/joshp123/xuezh/api/xuezh/v1;xuezhv1b\x06proto3"

var (
	file_xuezh_v1_xuezh_proto_rawDescOnce sync.Once
	file_xuezh_v1_xuezh_proto_rawDescData []byte
)

func file_xuezh_v1_xuezh_proto_rawDescGZIP() []byte {
	file_xuezh_v1_xuezh_proto_rawDescOnce.Do(func() {
		file_xuezh_v1_xuezh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xuezh_v1_xuezh_proto_rawDesc), len(file_xuezh_v1_xuezh_proto_rawDesc)))
	})
	return file_xuezh_v1_xuezh_proto_rawDescData
}

var file_xuezh_v1_xuezh_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_xuezh_v1_xuezh_proto_goTypes = []any{
	(*ServerArtifact)(nil),           // 0: xuezh.v1.ServerArtifact
	(*InlineFile)(nil),               // 1: xuezh.v1.InlineFile
	(*BackendInfo)(nil),              // 2: xuezh.v1.BackendInfo
	(*ReportPayload)(nil),            // 3: xuezh.v1.ReportPayload
	(*GetLearnerStateRequest)(nil),   // 4: xuezh.v1.GetLearnerStateRequest
	(*LearnerState)(nil),             // 5: xuezh.v1.LearnerState
	(*LearnerCardRow)(nil),           // 6: xuezh.v1.LearnerCardRow
	(*GetSnapshotRequest)(nil),       // 7: xuezh.v1.GetSnapshotRequest
	(*StartReviewRequest)(nil),       // 8: xuezh.v1.StartReviewRequest
	(*ReviewItem)(nil),               // 9: xuezh.v1.ReviewItem
	(*StartReviewResponse)(nil),      // 10: xuezh.v1.StartReviewResponse
	(*GradeReviewRequest)(nil),       // 11: xuezh.v1.GradeReviewRequest
	(*GradeReviewResponse)(nil),      // 12: xuezh.v1.GradeReviewResponse
	(*BuryReviewRequest)(nil),        // 13: xuezh.v1.BuryReviewRequest
	(*BuryReviewResponse)(nil),       // 14: xuezh.v1.BuryReviewResponse
	(*PreviewSRSRequest)(nil),        // 15: xuezh.v1.PreviewSRSRequest
	(*ReportHSKRequest)(nil),         // 16: xuezh.v1.ReportHSKRequest
	(*ReportMasteryRequest)(nil),     // 17: xuezh.v1.ReportMasteryRequest
	(*ReportDueRequest)(nil),         // 18: xuezh.v1.ReportDueRequest
	(*SynthesizeSpeechRequest)(nil),  // 19: xuezh.v1.SynthesizeSpeechRequest
	(*SynthesizeSpeechResponse)(nil), // 20: xuezh.v1.SynthesizeSpeechResponse
	(*ProcessVoiceRequest)(nil),      // 21: xuezh.v1.ProcessVoiceRequest
	(*ProcessVoiceResponse)(nil),     // 22: xuezh.v1.ProcessVoiceResponse
	(*PutContentRequest)(nil),        // 23: xuezh.v1.PutContentRequest
	(*GetContentRequest)(nil),        // 24: xuezh.v1.GetContentRequest
	(*ContentRecord)(nil),            // 25: xuezh.v1.ContentRecord
	(*GetContentResponse)(nil),       // 26: xuezh.v1.GetContentResponse
	(*LogEventRequest)(nil),          // 27: xuezh.v1.LogEventRequest
	(*EventRecord)(nil),              // 28: xuezh.v1.EventRecord
	(*ListEventsRequest)(nil),        // 29: xuezh.v1.ListEventsRequest
	(*ListEventsResponse)(nil),       // 30: xuezh.v1.ListEventsResponse
	(*DoctorRequest)(nil),            // 31: xuezh.v1.DoctorRequest
	(*DoctorResponse)(nil),           // 32: xuezh.v1.DoctorResponse
	(*DoctorCheck)(nil),              // 33: xuezh.v1.DoctorCheck
	(*structpb.Struct)(nil),          // 34: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),    // 35: google.protobuf.Timestamp
	(*structpb.Value)(nil),           // 36: google.protobuf.Value
}
var file_xuezh_v1_xuezh_proto_depIdxs = []int32{
	34, // 0: xuezh.v1.ReportPayload.data:type_name -> google.protobuf.Struct
	0,  // 1: xuezh.v1.ReportPayload.artifacts:type_name -> xuezh.v1.ServerArtifact
	34, // 2: xuezh.v1.ReportPayload.limits:type_name -> google.protobuf.Struct
	35, // 3: xuezh.v1.LearnerState.generated_at:type_name -> google.protobuf.Timestamp
	35, // 4: xuezh.v1.LearnerState.changed_at:type_name -> google.protobuf.Timestamp
	6,  // 5: xuezh.v1.LearnerState.cards:type_name -> xuezh.v1.LearnerCardRow
	36, // 6: xuezh.v1.LearnerCardRow.values:type_name -> google.protobuf.Value
	35, // 7: xuezh.v1.ReviewItem.due_at:type_name -> google.protobuf.Timestamp
	9,  // 8: xuezh.v1.StartReviewResponse.recall_items:type_name -> xuezh.v1.ReviewItem
	9,  // 9: xuezh.v1.StartReviewResponse.pronunciation_items:type_name -> xuezh.v1.ReviewItem
	35, // 10: xuezh.v1.StartReviewResponse.generated_at:type_name -> google.protobuf.Timestamp
	35, // 11: xuezh.v1.GradeReviewRequest.next_due:type_name -> google.protobuf.Timestamp
	35, // 12: xuezh.v1.GradeReviewResponse.recall_next_due:type_name -> google.protobuf.Timestamp
	35, // 13: xuezh.v1.GradeReviewResponse.pronunciation_next_due:type_name -> google.protobuf.Timestamp
	35, // 14: xuezh.v1.BuryReviewResponse.next_due:type_name -> google.protobuf.Timestamp
	2,  // 15: xuezh.v1.SynthesizeSpeechResponse.backend:type_name -> xuezh.v1.BackendInfo
	0,  // 16: xuezh.v1.SynthesizeSpeechResponse.artifacts:type_name -> xuezh.v1.ServerArtifact
	1,  // 17: xuezh.v1.SynthesizeSpeechResponse.audio:type_name -> xuezh.v1.InlineFile
	2,  // 18: xuezh.v1.ProcessVoiceResponse.backend:type_name -> xuezh.v1.BackendInfo
	34, // 19: xuezh.v1.ProcessVoiceResponse.assessment:type_name -> google.protobuf.Struct
	34, // 20: xuezh.v1.ProcessVoiceResponse.transcript:type_name -> google.protobuf.Struct
	0,  // 21: xuezh.v1.ProcessVoiceResponse.artifacts:type_name -> xuezh.v1.ServerArtifact
	1,  // 22: xuezh.v1.ProcessVoiceResponse.feedback_audio:type_name -> xuezh.v1.InlineFile
	34, // 23: xuezh.v1.ProcessVoiceResponse.limits:type_name -> google.protobuf.Struct
	0,  // 24: xuezh.v1.ContentRecord.artifacts:type_name -> xuezh.v1.ServerArtifact
	25, // 25: xuezh.v1.GetContentResponse.record:type_name -> xuezh.v1.ContentRecord
	35, // 26: xuezh.v1.EventRecord.ts:type_name -> google.protobuf.Timestamp
	28, // 27: xuezh.v1.ListEventsResponse.events:type_name -> xuezh.v1.EventRecord
	33, // 28: xuezh.v1.DoctorResponse.checks:type_name -> xuezh.v1.DoctorCheck
	34, // 29: xuezh.v1.DoctorCheck.details:type_name -> google.protobuf.Struct
	4,  // 30: xuezh.v1.XuezhService.GetLearnerState:input_type -> xuezh.v1.GetLearnerStateRequest
	7,  // 31: xuezh.v1.XuezhService.GetSnapshot:input_type -> xuezh.v1.GetSnapshotRequest
	8,  // 32: xuezh.v1.XuezhService.StartReview:input_type -> xuezh.v1.StartReviewRequest
	11, // 33: xuezh.v1.XuezhService.GradeReview:input_type -> xuezh.v1.GradeReviewRequest
	13, // 34: xuezh.v1.XuezhService.BuryReview:input_type -> xuezh.v1.BuryReviewRequest
	15, // 35: xuezh.v1.XuezhService.PreviewSRS:input_type -> xuezh.v1.PreviewSRSRequest
	16, // 36: xuezh.v1.XuezhService.ReportHSK:input_type -> xuezh.v1.ReportHSKRequest
	17, // 37: xuezh.v1.XuezhService.ReportMastery:input_type -> xuezh.v1.ReportMasteryRequest
	18, // 38: xuezh.v1.XuezhService.ReportDue:input_type -> xuezh.v1.ReportDueRequest
	19, // 39: xuezh.v1.XuezhService.SynthesizeSpeech:input_type -> xuezh.v1.SynthesizeSpeechRequest
	21, // 40: xuezh.v1.XuezhService.ProcessVoice:input_type -> xuezh.v1.ProcessVoiceRequest
	23, // 41: xuezh.v1.XuezhService.PutContent:input_type -> xuezh.v1.PutContentRequest
	24, // 42: xuezh.v1.XuezhService.GetContent:input_type -> xuezh.v1.GetContentRequest
	27, // 43: xuezh.v1.XuezhService.LogEvent:input_type -> xuezh.v1.LogEventRequest
	29, // 44: xuezh.v1.XuezhService.ListEvents:input_type -> xuezh.v1.ListEventsRequest
	31, // 45: xuezh.v1.XuezhService.Doctor:input_type -> xuezh.v1.DoctorRequest
	5,  // 46: xuezh.v1.XuezhService.GetLearnerState:output_type -> xuezh.v1.LearnerState
	3,  // 47: xuezh.v1.XuezhService.GetSnapshot:output_type -> xuezh.v1.ReportPayload
	10, // 48: xuezh.v1.XuezhService.StartReview:output_type -> xuezh.v1.StartReviewResponse
	12, // 49: xuezh.v1.XuezhService.GradeReview:output_type -> xuezh.v1.GradeReviewResponse
	14, // 50: xuezh.v1.XuezhService.BuryReview:output_type -> xuezh.v1.BuryReviewResponse
	3,  // 51: xuezh.v1.XuezhService.PreviewSRS:output_type -> xuezh.v1.ReportPayload
	3,  // 52: xuezh.v1.XuezhService.ReportHSK:output_type -> xuezh.v1.ReportPayload
	3,  // 53: xuezh.v1.XuezhService.ReportMastery:output_type -> xuezh.v1.ReportPayload
	3,  // 54: xuezh.v1.XuezhService.ReportDue:output_type -> xuezh.v1.ReportPayload
	20, // 55: xuezh.v1.XuezhService.SynthesizeSpeech:output_type -> xuezh.v1.SynthesizeSpeechResponse
	22, // 56: xuezh.v1.XuezhService.ProcessVoice:output_type -> xuezh.v1.ProcessVoiceResponse
	25, // 57: xuezh.v1.XuezhService.PutContent:output_type -> xuezh.v1.ContentRecord
	26, // 58: xuezh.v1.XuezhService.GetContent:output_type -> xuezh.v1.GetContentResponse
	28, // 59: xuezh.v1.XuezhService.LogEvent:output_type -> xuezh.v1.EventRecord
	30, // 60: xuezh.v1.XuezhService.ListEvents:output_type -> xuezh.v1.ListEventsResponse
	32, // 61: xuezh.v1.XuezhService.Doctor:output_type -> xuezh.v1.DoctorResponse
	46, // [46:62] is the sub-list for method output_type
	30, // [30:46] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_xuezh_v1_xuezh_proto_init() }
func file_xuezh_v1_xuezh_proto_init() {
	if File_xuezh_v1_xuezh_proto != nil {
		return
	}
	file_xuezh_v1_xuezh_proto_msgTypes[0].OneofWrappers = []any{}
	file_xuezh_v1_xuezh_proto_msgTypes[11].OneofWrappers = []any{}
	file_xuezh_v1_xuezh_proto_msgTypes[12].OneofWrappers = []any{}
	file_xuezh_v1_xuezh_proto_msgTypes[27].OneofWrappers = []any{}
	file_xuezh_v1_xuezh_proto_msgTypes[28].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xuezh_v1_xuezh_proto_rawDesc), len(file_xuezh_v1_xuezh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xuezh_v1_xuezh_proto_goTypes,
		DependencyIndexes: file_xuezh_v1_xuezh_proto_depIdxs,
		MessageInfos:      file_xuezh_v1_xuezh_proto_msgTypes,
	}.Build()
	File_xuezh_v1_xuezh_proto = out.File
	file_xuezh_v1_xuezh_proto_goTypes = nil
	file_xuezh_v1_xuezh_proto_depIdxs = nil
}
